# cloudformation.yaml
Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.micro"
      ImageId: "ami-0c55b159cbfafe1f0"  # Amazon Linux 2 AMI
      KeyName: "my-key-pair"
      SecurityGroups:
        - "default"